### PR TITLE
Fixed duplicate message in console by using a separate format

### LINKED ISSUE #56: Issues with messages sent to console.
So there's 2 issues currently with messages sent by players when they show in console.

First of all in spigot even if you clear the recipients list, the message will still be sent to the console. You have to completely cancel the event for it to not be sent.
This means since we send the message to the console ourselves there will be a duplicate. And yes at least for the normal ChatChannels the console will always be a target as shown here: https://github.com/HelpChat/ChatChat/blob/42e13413aeaca707e9c05160f49ba0d804f866e7/plugin/src/main/java/at/helpch/chatchat/channel/ChatChannel.java#L49
https://github.com/HelpChat/ChatChat/blob/42e13413aeaca707e9c05160f49ba0d804f866e7/plugin/src/main/java/at/helpch/chatchat/user/UsersHolder.java#L27

The second issue is that our format just send the message itself but not the formatting part. so no player names, etc. 
image

### PR DESCRIPTION
**Pull request by BlitzOffline**
So I've started testing some stuff today to find a good fix for the message sent in console being duplicated and it turns out you don't actually have to use the string format specifiers in the message.

I've made this a draft PR as my only test is on Paper 1.19. I have to test on spigot(possibly 1.13) as well to make sure its not actually a thing that only works on paper or on newer versions.

Fixes #56 

EDIT: Tested on 1.13.2 and it seems to work just fine!

### CODE REVIEW

File: plugin/src/main/java/at/helpch/chatchat/format/ConsoleFormat.java [hunk 1]
```diff
@@ -0,0 +1,57 @@
+package at.helpch.chatchat.format;
+
+import at.helpch.chatchat.api.Format;
+import java.util.Collections;
+import java.util.List;
+import java.util.Map;
+import org.jetbrains.annotations.NotNull;
+
+public class ConsoleFormat implements Format {
```
Comment (Kqliber) [inline plugin/src/main/java/at/helpch/chatchat/format/ConsoleFormat.java:9]: by the looks of it, this is the same as PMFormat, if so, cant we make this into a more generic class, like BasicFormat or smth? as both don't need priorities

Comment (BlitzOffline) [reply plugin/src/main/java/at/helpch/chatchat/format/ConsoleFormat.java:9]: I did think about it but I just didn't have time to do it so I said I'm going to do it in another PR. I just noticed I forgot to annotate the class tho. I don't even know if that's needed

**Review by Kqliber — APPROVED** [review]
